services:
  # kubectl exec -n simple-syllabus postgres-0 -c postgres -- sh -c 'pg_dump -U "$POSTGRES_USER" --no-owner --no-acl --clean --if-exists "$POSTGRES_DB"' > /tmp/prod_dump.sql && docker exec -i snowsetools-db-1 psql -U syllabus_user -d snow_se_tools_dev < /tmp/prod_dump.sql
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: syllabus_user
      POSTGRES_PASSWORD: syllabus_pass
      POSTGRES_DB: snow_se_tools_dev
    volumes:
      - ./k8s/base/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U syllabus_user -d snow_se_tools_dev",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 4000:4000
    command: |
      mix phx.server
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: ecto://syllabus_user:syllabus_pass@db/snow_se_tools_dev
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_SERVER: "true"
      MIX_ENV: dev
      OIDC_REDIRECT_URI: "http://localhost:4000/auth/callback"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
