apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: simple-syllabus-reporter
      spec:
        template:
          spec:
            containers:
              - name: webapp
                env:
                  - name: PHX_HOST
                    value: "alexsimplesyllabuscheck.snowse.io"
                  - name: OIDC_REDIRECT_URI
                    value: "https://alexsimplesyllabuscheck.snowse.io/auth/callback"

    target:
      kind: Deployment
      name: simple-syllabus-reporter
  - patch: |-
      apiVersion: networking.istio.io/v1beta1
      kind: VirtualService
      metadata:
        name: simple-syllabus
      spec:
        gateways:
          - istio-system/main-gateway
        hosts:
          - "alexsimplesyllabuscheck.snowse.io"
    target:
      kind: VirtualService
      name: simple-syllabus
