apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: simple-syllabus-reporter
      spec:
        template:
          spec:
            containers:
              - name: webapp
                env:
                  - name: PHX_HOST
                    value: "alexsimplesyllabuscheck.snowse.io"
                  - name: OIDC_REDIRECT_URI
                    value: "https://alexsimplesyllabuscheck.snowse.io/auth/callback"

    target:
      kind: Deployment
      name: simple-syllabus-reporter
  - patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: simple-syllabus
      spec:
        parentRefs:
          - name: main-gateway
            namespace: istio-system
        hostnames:
          - "alexsimplesyllabuscheck.snowse.io"
    target:
      kind: HTTPRoute
      name: simple-syllabus
