defmodule SnowSeToolsWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :snow_se_tools

  # The session is stored in the cookie, signed AND encrypted: it carries the
  # OIDC refresh token and userinfo claims, which must not be readable client-side.
  # Salts are combined with SECRET_KEY_BASE, so committing them is safe.
  # max_age bounds how long a stolen cookie stays verifiable.
  @session_options [
    store: :cookie,
    key: "_snow_se_tools_key",
    signing_salt: "hrpbGw22",
    encryption_salt: "kQ7vX2pLm9sN4dRz",
    max_age: 60 * 60 * 24 * 14,
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :snow_se_tools,
    gzip: not code_reloading?,
    only: SnowSeToolsWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug SnowSeToolsWeb.Plugs.HealthCheck

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.RewriteOn, [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SnowSeToolsWeb.Router
end
